[package]
name = "raamattu-test"
version = "0.1.0"
edition = "2021"

[dependencies]
thirtyfour = { version = "0.35" }
tokio = { version = "1.42", features = ["full"] }
selenium-manager = { git = "https://github.com/SeleniumHQ/selenium", branch = "trunk" }
